### ISSUE TITLE
Adding Buttons

### ISSUE THREAD

**Issue by mexicanhaze** [morpheusthewhite/NordPy#13]
Hi and thanks for the app, I've been waiting for ages for one of these (nordvpn told me they wouldn't bother)
I was going to suggest adding a button that kills IPv6 with
 `sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1`
 but then realised that this would probably only work on Debian (and forks).
So I thought why not suggest adding customisable buttons where the user could choose a system command to run.
For example I have UFW so implementing a killswitch  can be done with these two commands : 
```
sudo ufw default deny outgoing
sudo ufw allow out on tun0 from any to any 
```
(I know you can do it directly with iptables but never tried)

Adding customisable buttons would give each user the opportunity to implement a killswitch (or whatever) for their own distro. You wouldn't have to bother finding a "universal" solution that would work no matter the distro. Each user would pick their own solution or option and go with it.

That's all (thanks again for the app)

**Comment by morpheusthewhite** [comment]
So you suggest that I should place a new button that invokes some custom user script written by the users instead of writing a universal solution? I don't think it's a good idea, I want to propose a complete work, and the solution will probably be the use of iptables, as suggested [in a previous issue](https://github.com/morpheusthewhite/NordPy/issues/8).

Thank you for your appreciation and the interesting discussion
